# Project: Crackme 01
# Makefile created by Embarcadero Dev-C++ 6.3

 
CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = crackme01_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
PACKER	 = upx.exe
LIBS     = -L"D:/Program Files/retoolkit/programming/devcpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -mwindows -m32
INCS     = -I"D:/Program Files/retoolkit/programming/devcpp/TDM-GCC-64/include" -I"D:/Program Files/retoolkit/programming/devcpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Program Files/retoolkit/programming/devcpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Program Files/retoolkit/programming/devcpp/TDM-GCC-64/include" -I"D:/Program Files/retoolkit/programming/devcpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Program Files/retoolkit/programming/devcpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Program Files/retoolkit/programming/devcpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = crackme01.exe
BIN_UPX  = crackme01-upx.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
DEL      = D:\Program Files\retoolkit\programming\devcpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

$(BIN_UPX): $(BIN)
	$(UPX) -9 $(BIN) -o $(BIN_UPX)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

crackme01_private.res: crackme01_private.rc resource.rc
	$(WINDRES) -i crackme01_private.rc -F pe-i386 --input-format=rc -o crackme01_private.res -O coff 

